# Generated by Django 2.1.5 on 2019-02-01 09:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grazhdanstvo', models.CharField(max_length=30)),
                ('grazhdanstvo2', models.CharField(default='USA', max_length=30)),
                ('kratnost', models.CharField(max_length=30)),
                ('familiya', models.CharField(default='firstname', max_length=30)),
                ('imya', models.CharField(default='secondname', max_length=30)),
                ('data_rozh', models.DateField(default=datetime.date.today)),
                ('nomer_pass', models.IntegerField(default=1111111111)),
                ('prin_organiz', models.CharField(default='', max_length=10000)),
                ('dop_svedeniya', models.CharField(default='', max_length=10000)),
            ],
        ),
    ]
