# Generated by Django 2.1.5 on 2019-02-13 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Dates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.DateField()),
                ('departure', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Form1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familyname', models.CharField(max_length=30)),
                ('firstname', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('sex', models.CharField(max_length=10)),
                ('goal', models.CharField(max_length=30)),
                ('birthday', models.DateField()),
                ('passport', models.TextField()),
                ('entry', models.DateField()),
                ('departure', models.DateField()),
                ('nationality', models.TextField()),
                ('multiplicity', models.TextField()),
                ('confirmation', models.TextField()),
                ('date', models.DateField()),
                ('placement', models.TextField()),
                ('rout', models.TextField()),
                ('hostorganization', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Form2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familyname', models.CharField(max_length=30)),
                ('firstname', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('sex', models.CharField(max_length=10)),
                ('goal', models.CharField(max_length=30)),
                ('birthday', models.DateField()),
                ('passport', models.TextField()),
                ('entry', models.DateField()),
                ('departure', models.DateField()),
                ('nationality', models.TextField()),
                ('multiplicity', models.TextField()),
                ('confirmation', models.TextField()),
                ('date', models.DateField()),
                ('placement', models.TextField()),
                ('rout', models.TextField()),
                ('hostorganization', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GroupMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familyname', models.CharField(default='', max_length=30)),
                ('firstname', models.CharField(default='', max_length=30)),
                ('name', models.CharField(default='', max_length=30)),
                ('lastname', models.CharField(default='', max_length=30)),
                ('birthday', models.DateField(default='')),
                ('passport', models.TextField(default='')),
                ('nationality', models.TextField(default='')),
                ('form2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Form2')),
            ],
        ),
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationality', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Routs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rout', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ships',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='dates',
            name='ship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Ships'),
        ),
    ]
