# Generated by Django 2.1.5 on 2019-02-06 20:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familyname', models.CharField(default='familyname', max_length=30)),
                ('firstname', models.CharField(default='firstname', max_length=30)),
                ('name', models.CharField(default='name', max_length=30)),
                ('lastname', models.CharField(default='lastname', max_length=30)),
                ('sex', models.CharField(default='sex', max_length=10)),
                ('goal', models.CharField(default='goal', max_length=30)),
                ('birthday', models.DateField(default=datetime.date(2019, 1, 1))),
                ('passport', models.IntegerField(default=1111111111)),
                ('entry', models.DateField(default=datetime.date(2019, 1, 1))),
                ('departure', models.DateField(default=datetime.date(2019, 1, 1))),
                ('nationality', models.CharField(default='nationality', max_length=1000)),
                ('multiplicity', models.CharField(default='multipliticy', max_length=1000)),
                ('confirmation', models.CharField(default='confirmation', max_length=1000)),
                ('date', models.DateField(default=datetime.date(2019, 1, 1))),
                ('placement', models.CharField(default='', max_length=10000)),
                ('root', models.CharField(default='', max_length=10000)),
                ('hostorganization', models.CharField(default='', max_length=10000)),
            ],
        ),
        migrations.DeleteModel(
            name='Data',
        ),
    ]
