# Generated by Django 2.1.5 on 2019-02-06 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190207_0357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form1',
            name='multiplicity',
            field=models.CharField(default='multiplicity', max_length=1000),
        ),
    ]
