# Generated by Django 2.1.5 on 2019-02-01 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_data_a'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='age',
        ),
        migrations.RemoveField(
            model_name='data',
            name='name',
        ),
        migrations.AddField(
            model_name='data',
            name='grazhdanstvo',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='kratnost',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
