# Generated by Django 2.1.5 on 2019-02-16 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190215_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='form2',
            name='additionalinfo',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='additionalinfo',
            name='default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='dates',
            name='default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='nationality',
            name='default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='organizations',
            name='default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='placements',
            name='default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='routs',
            name='default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ships',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
