# Generated by Django 2.1.5 on 2019-02-07 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190207_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form1',
            name='birthday',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='form1',
            name='confirmation',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='form1',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='form1',
            name='departure',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='form1',
            name='entry',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='form1',
            name='goal',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='form1',
            name='hostorganization',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='form1',
            name='multiplicity',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='form1',
            name='nationality',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='form1',
            name='placement',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='form1',
            name='root',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='form1',
            name='sex',
            field=models.CharField(max_length=10),
        ),
    ]
