# Generated by Django 2.1.5 on 2019-02-07 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190207_1010'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form1',
            old_name='root',
            new_name='rout',
        ),
    ]
