# Generated by Django 2.1.5 on 2019-02-07 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190207_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form1',
            name='familyname',
            field=models.CharField(default='Фамилия', max_length=30),
        ),
    ]
