# Generated by Django 2.1.5 on 2019-02-21 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190220_0723'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner', models.TextField()),
                ('default', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='form1',
            old_name='confirmation',
            new_name='partner',
        ),
        migrations.RenameField(
            model_name='form2',
            old_name='confirmation',
            new_name='partner',
        ),
    ]
