# Generated by Django 2.1.5 on 2019-02-07 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190208_0419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form1',
            name='familyname',
            field=models.CharField(max_length=30),
        ),
    ]
