# Generated by Django 2.1.5 on 2019-02-22 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20190221_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='form2',
            name='visa_type',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
