# Generated by Django 2.1.5 on 2019-02-07 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20190208_0421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form1',
            name='hostorganization',
        ),
        migrations.RemoveField(
            model_name='form1',
            name='placement',
        ),
        migrations.RemoveField(
            model_name='form1',
            name='rout',
        ),
    ]
