# Generated by Django 2.1.5 on 2019-02-07 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20190208_0524'),
    ]

    operations = [
        migrations.AddField(
            model_name='form1',
            name='gen',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
