# Generated by Django 2.1.5 on 2019-02-09 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20190209_0411'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familyname', models.CharField(max_length=30)),
                ('firstname', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('sex', models.CharField(max_length=10)),
                ('goal', models.CharField(max_length=30)),
                ('birthday', models.DateField()),
                ('passport', models.TextField()),
                ('entry', models.DateField()),
                ('departure', models.DateField()),
                ('nationality', models.TextField()),
                ('multiplicity', models.TextField()),
                ('confirmation', models.TextField()),
                ('date', models.DateField()),
                ('placement', models.TextField()),
                ('rout', models.TextField()),
                ('hostorganization', models.TextField()),
            ],
        ),
    ]
