# Generated by Django 2.1.5 on 2019-02-10 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_form2'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familyname', models.CharField(default='', max_length=30)),
                ('firstname', models.CharField(default='', max_length=30)),
                ('name', models.CharField(default='', max_length=30)),
                ('lastname', models.CharField(default='', max_length=30)),
                ('birthday', models.DateField(default='')),
                ('passport', models.TextField(default='')),
                ('nationality', models.TextField(default='')),
                ('form2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Form2')),
            ],
        ),
    ]
