# Generated by Django 2.1.5 on 2019-02-12 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20190213_0251'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Routs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rout', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='ships',
            name='placement',
        ),
        migrations.RemoveField(
            model_name='ships',
            name='rout',
        ),
    ]
