from django.db import models
import datetime
import re

# таблица app_data
class Form1(models.Model):
    familyname = models.CharField(max_length=30)
    firstname = models.CharField(max_length=30)
    name = models.CharField(max_length=30)
    lastname = models.CharField(max_length=30)
    sex = models.CharField(max_length=10)
    goal = models.CharField(max_length=30)
    birthday = models.DateField()
    passport = models.TextField()
    entry = models.DateField()
    departure = models.DateField()
    nationality = models.TextField()
    multiplicity = models.TextField()
    confirmation = models.TextField()
    date = models.DateField()
    placement = models.TextField()
    rout = models.TextField()
    hostorganization = models.TextField()

class Form2(models.Model):
    familyname = models.CharField(max_length=30)
    firstname = models.CharField(max_length=30)
    name = models.CharField(max_length=30)
    lastname = models.CharField(max_length=30)
    sex = models.CharField(max_length=10)
    goal = models.CharField(max_length=30)
    birthday = models.DateField()
    passport = models.TextField()
    entry = models.DateField()
    departure = models.DateField()
    nationality = models.TextField()
    multiplicity = models.TextField()
    confirmation = models.TextField()
    date = models.DateField()
    placement = models.TextField()
    rout = models.TextField()
    hostorganization = models.TextField()

    g_familyname1 = models.CharField(max_length=30)
    g_firstname1 = models.CharField(max_length=30)
    g_name1 = models.CharField(max_length=30)
    g_lastname1 = models.CharField(max_length=30)
    g_birthday1 = models.DateField()
    g_passport1 = models.TextField()
    g_nationality1 = models.TextField()

    g_familyname2 = models.CharField(max_length=30)
    g_firstname2 = models.CharField(max_length=30)
    g_name2 = models.CharField(max_length=30)
    g_lastname2 = models.CharField(max_length=30)
    g_birthday2 = models.DateField()
    g_passport2 = models.TextField()
    g_nationality2 = models.TextField()

    g_familyname3 = models.CharField(max_length=30)
    g_firstname3 = models.CharField(max_length=30)
    g_name3 = models.CharField(max_length=30)
    g_lastname3 = models.CharField(max_length=30)
    g_birthday3 = models.DateField()
    g_passport3 = models.TextField()
    g_nationality3 = models.TextField()

    g_familyname4 = models.CharField(max_length=30)
    g_firstname4 = models.CharField(max_length=30)
    g_name4 = models.CharField(max_length=30)
    g_lastname4 = models.CharField(max_length=30)
    g_birthday4 = models.DateField()
    g_passport4 = models.TextField()
    g_nationality4 = models.TextField()

    g_familyname5 = models.CharField(max_length=30)
    g_firstname5 = models.CharField(max_length=30)
    g_name5 = models.CharField(max_length=30)
    g_lastname5 = models.CharField(max_length=30)
    g_birthday5 = models.DateField()
    g_passport5 = models.TextField()
    g_nationality5 = models.TextField()

    g_familyname6 = models.CharField(max_length=30)
    g_firstname6 = models.CharField(max_length=30)
    g_name6 = models.CharField(max_length=30)
    g_lastname6 = models.CharField(max_length=30)
    g_birthday6 = models.DateField()
    g_passport6 = models.TextField()
    g_nationality6 = models.TextField()

    g_familyname7 = models.CharField(max_length=30)
    g_firstname7 = models.CharField(max_length=30)
    g_name7 = models.CharField(max_length=30)
    g_lastname7 = models.CharField(max_length=30)
    g_birthday7 = models.DateField()
    g_passport7 = models.TextField()
    g_nationality7 = models.TextField()

    g_familyname8 = models.CharField(max_length=30)
    g_firstname8 = models.CharField(max_length=30)
    g_name8 = models.CharField(max_length=30)
    g_lastname8 = models.CharField(max_length=30)
    g_birthday8 = models.DateField()
    g_passport8 = models.TextField()
    g_nationality8 = models.TextField()

    g_familyname9 = models.CharField(max_length=30)
    g_firstname9 = models.CharField(max_length=30)
    g_name9 = models.CharField(max_length=30)
    g_lastname9 = models.CharField(max_length=30)
    g_birthday9 = models.DateField()
    g_passport9 = models.TextField()
    g_nationality9 = models.TextField()

    g_familyname10 = models.CharField(max_length=30)
    g_firstname10 = models.CharField(max_length=30)
    g_name10 = models.CharField(max_length=30)
    g_lastname10 = models.CharField(max_length=30)
    g_birthday10 = models.DateField()
    g_passport10 = models.TextField()
    g_nationality10 = models.TextField()


#https://djbook.ru/rel1.6/topics/forms/modelforms.html

